project_name: bfc

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - DOCKER_CLI_EXPERIMENTAL=enabled

release:
  prerelease: auto
  draft: false
  github:
    owner: hoshsadiq
    name: big-fat-converter

snapshot:
  name_template: "{{ .Version }}+next+{{ .ShortCommit }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

builds:
  - id: bfc
    main: ./cmd/bfc
    binary: bfc
    goos:
      - linux
      - darwin
      - freebsd
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64

    ldflags:
      - -s -w
      - -X 'github.com/hoshsadiq/big-fat-converter/version.Version={{.Version}}'
      - -X 'github.com/hoshsadiq/big-fat-converter/version.GitCommit={{.ShortCommit}}'
      - -X 'github.com/hoshsadiq/big-fat-converter/version.BuildMeta={{.Timestamp}}'
      - -X 'github.com/hoshsadiq/big-fat-converter/version.ProjectName=Big Fat Converter'
      - -X 'github.com/hoshsadiq/big-fat-converter/version.ProjectURL=https://github.com/hoshsadiq/big-fat-converter'

dockers:
  - &docker_build
    goos: linux
    goarch: amd64
    ids:
      - bfc
    skip_push: false
    use_buildx: true

    image_templates:
      - &docker_tag_amd64 "ghcr.io/hoshsadiq/big-fat-converter:{{ .Tag }}-amd64"
      - &docker_major_amd64 "ghcr.io/hoshsadiq/big-fat-converter:v{{ .Major }}-amd64"
      - &docker_major_minor_amd64 "ghcr.io/hoshsadiq/big-fat-converter:v{{ .Major }}.{{ .Minor }}-amd64"
      - &docker_latest_amd64 "ghcr.io/hoshsadiq/big-fat-converter:latest-amd64"

    build_flag_templates:
      - "--platform=linux/amd64"
      - &build_flag_tmpl_date "--label=org.opencontainers.image.created={{.Date}}"
      - &build_flag_tmpl_name "--label=org.opencontainers.image.name={{.ProjectName}}"
      - &build_flag_tmpl_commit "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - &build_flag_tmpl_version "--label=org.opencontainers.image.version={{.Version}}"
      - &build_flag_tmpl_url "--label=org.opencontainers.image.source={{.GitURL}}"

    dockerfile: Dockerfile.goreleaser

  - <<: *docker_build
    goarch: arm
    goarm: 7
    image_templates:
      - &docker_tag_arm32v7 "ghcr.io/hoshsadiq/big-fat-converter:latest-arm32v7"
      - &docker_major_arm32v7 "ghcr.io/hoshsadiq/big-fat-converter:{{ .Tag }}-arm32v7"
      - &docker_major_minor_arm32v7 "ghcr.io/hoshsadiq/big-fat-converter:v{{ .Major }}-arm32v7"
      - &docker_latest_arm32v7 "ghcr.io/hoshsadiq/big-fat-converter:v{{ .Major }}.{{ .Minor }}-arm32v7"

    build_flag_templates:
      - "--platform=linux/arm"
      - *build_flag_tmpl_date
      - *build_flag_tmpl_name
      - *build_flag_tmpl_commit
      - *build_flag_tmpl_version
      - *build_flag_tmpl_url

  - <<: *docker_build
    goarch: arm
    goarm: 6
    image_templates:
      - &docker_tag_arm32v6 "ghcr.io/hoshsadiq/big-fat-converter:latest-arm32v6"
      - &docker_major_arm32v6 "ghcr.io/hoshsadiq/big-fat-converter:{{ .Tag }}-arm32v6"
      - &docker_major_minor_arm32v6 "ghcr.io/hoshsadiq/big-fat-converter:v{{ .Major }}-arm32v6"
      - &docker_latest_arm32v6 "ghcr.io/hoshsadiq/big-fat-converter:v{{ .Major }}.{{ .Minor }}-arm32v6"

    build_flag_templates:
      - "--platform=linux/arm/v6"
      - *build_flag_tmpl_date
      - *build_flag_tmpl_name
      - *build_flag_tmpl_commit
      - *build_flag_tmpl_version
      - *build_flag_tmpl_url

  - <<: *docker_build
    goarch: arm64
    image_templates:
      - &docker_tag_arm64v8 "ghcr.io/hoshsadiq/big-fat-converter:latest-arm64v8"
      - &docker_major_arm64v8 "ghcr.io/hoshsadiq/big-fat-converter:{{ .Tag }}-arm64v8"
      - &docker_major_minor_arm64v8 "ghcr.io/hoshsadiq/big-fat-converter:v{{ .Major }}-arm64v8"
      - &docker_latest_arm64v8 "ghcr.io/hoshsadiq/big-fat-converter:v{{ .Major }}.{{ .Minor }}-arm64v8"

    build_flag_templates:
      - "--platform=linux/arm64"
      - *build_flag_tmpl_date
      - *build_flag_tmpl_name
      - *build_flag_tmpl_commit
      - *build_flag_tmpl_version
      - *build_flag_tmpl_url

docker_manifests:
  - name_template: "ghcr.io/hoshsadiq/big-fat-converter:latest"
    image_templates:
      - *docker_latest_amd64
      - *docker_latest_arm32v6
      - *docker_latest_arm32v7
      - *docker_latest_arm64v8
  - name_template: "ghcr.io/hoshsadiq/big-fat-converter:{{ .Tag }}"
    image_templates:
      - *docker_tag_amd64
      - *docker_tag_arm32v6
      - *docker_tag_arm32v7
      - *docker_tag_arm64v8
  - name_template: "ghcr.io/hoshsadiq/big-fat-converter:v{{ .Major }}"
    image_templates:
      - *docker_major_amd64
      - *docker_major_arm32v6
      - *docker_major_arm32v7
      - *docker_major_arm64v8
  - name_template: "ghcr.io/hoshsadiq/big-fat-converter:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - *docker_major_minor_amd64
      - *docker_major_minor_arm32v6
      - *docker_major_minor_arm32v7
      - *docker_major_minor_arm64v8
